# Generated by Django 5.0.2 on 2024-02-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='numero_serie',
            new_name='codigo_barras',
        ),
    ]
